version: "3.7"
services:
  app:
    build:
      # args:
      #   user: user
      #   uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app-host
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - '${APP_NAME}'

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db-host
    restart: unless-stopped
    ports:
      - "3090:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - '${APP_NAME}'

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx-host
    restart: unless-stopped
    ports:
      - ${USER_PORT}:80
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - '${APP_NAME}'
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - '${APP_NAME}'

networks:
  todo:
    driver: bridge
